version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=canal
      - MYSQL_PASSWORD=canal
    command: --default-time_zone = '+8:00' --log-bin=mysql-bin --binlog-format=ROW --server_id=1
  canal-server:
    image: canal/canal-server:v1.1.4
    hostname: ${DOCKER_HOST_IP}
    ports:
      - 9100:9100
      - 11110:11110
      - 11111:11111
      - 11112:11112
    environment:
      - canal.destinations=${CANAL_DESTINATIONS}
      - canal.instance.master.address=mysql:3306
      - canal.instance.dbUsername=root
      - canal.instance.dbPassword=123456
      - canal.instance.connectionCharset=UTF-8
      - canal.instance.tsdb.enable=true
      - canal.instance.gtidon=false
      - canal.instance.filter.regex=${CANAL_FILTER_REGEX}
